---
  - name: copy kafka config
    hosts: kafka
    gather_facts: false
    remote_user: ec2-user
    tasks:
      
      - copy:
            src: ../resources/kafka0/
            dest: ~/resources/kafka0/

  - name: Start kafka Nodes
    hosts: kafka
    gather_facts: false
    remote_user: ec2-user
    tasks:
      - name: Start Kafka
        command: "{{item}}"
        with_items:
            - "docker-compose up -d --build"
        args:
           chdir: ~/resources/kafka0/
        register: node_result


