---
  - name: copy kafka config
    hosts: kafka
    gather_facts: false
    remote_user: ec2-user
    tasks:
      
      - copy:
            src: ../resources/zookeeper/
            dest: ~/resources/zookeeper/

  - name: copy kafka config
    hosts: kafka1
    gather_facts: false
    remote_user: ec2-user
    tasks:
      
      - copy:
            src: ../resources/zookeeper/env/2.env
            dest: ~/resources/zookeeper/.env
  
  - name: copy kafka config
    hosts: kafka0
    gather_facts: false
    remote_user: ec2-user
    tasks:
      
      - copy:
            src: ../resources/zookeeper/env/1.env
            dest: ~/resources/zookeeper/.env

  - name: copy kafka config
    hosts: kafka2
    gather_facts: false
    remote_user: ec2-user
    tasks:
      
      - copy:
            src: ../resources/zookeeper/env/3.env
            dest: ~/resources/zookeeper/.env

  - name: Start Zookeeper Nodes
    hosts: kafka
    gather_facts: false
    remote_user: ec2-user
    tasks:
      - name: Start Zookeeper
        command: "{{item}}"
        with_items:
            - "docker-compose up -d"
        args:
           chdir: ~/resources/zookeeper/
        register: node_result


