---
  - name: copy kafka config
    hosts: kafka
    gather_facts: false
    remote_user: ec2-user
    tasks:
      
      - copy:
            src: ../resources/kafka/
            dest: ~/resources/kafka/


  - name: copy kafka config
    hosts: kafka0
    gather_facts: false
    remote_user: ec2-user
    tasks:
      
      - copy:
            src: ../resources/kafka/env/0.env
            dest: ~/resources/kafka/.env

  - name: copy kafka config
    hosts: kafka1
    gather_facts: false
    remote_user: ec2-user
    tasks:
      
      - copy:
            src: ../resources/kafka/env/1.env
            dest: ~/resources/kafka/.env

  - name: copy kafka config
    hosts: kafka2
    gather_facts: false
    remote_user: ec2-user
    tasks:
      
      - copy:
            src: ../resources/kafka/env/2.env
            dest: ~/resources/kafka/.env

  - name: Start kafka Nodes
    hosts: kafka
    gather_facts: false
    remote_user: ec2-user
    tasks:
      - name: Start Kafka
        command: "{{item}}"
        with_items:
            - "docker-compose up -d --build"
        args:
           chdir: ~/resources/kafka/
        register: node_result


