---
  - name: Start kafka Nodes
    hosts: kafka
    gather_facts: false
    remote_user: ec2-user
    tasks:
      - name: Start Kafka
        command: "{{item}}"
        with_items:
            - docker-compose up -d --build
        register: node_result

     

  
