---
  - name: Stop kafka Nodes
    hosts: kafka
    gather_facts: false
    remote_user: ec2-user
    tasks:
      - name: Stop kafka Client
        command: docker-compose down
        args:
           chdir: ~/resources/kafka0/
        register: node_result

 
